openapi: 3.0.0
info:
  title: Health App API
  version: 1.0.0
  description: API for managing products and daily consumption

servers:
  - url: http://localhost:3000

paths:
  /products:
    get:
      summary: Search products
      description: Search for products by title using a query string
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: The search string
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /api/private/day/{date}:
    get:
      summary: Get consumed products and total kcal for a specific day
      tags:
        - Day
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer your_jwt_token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Info for the specified day
          content:
            application/json:
              schema:
                type: object
                properties:
                  consumedProducts:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConsumedProduct'
                  totalKcal:
                    type: number
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/private/day/{date}/consumed:
    post:
      summary: Add a consumed product to a specific day
      tags:
        - Day
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer your_jwt_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                weight:
                  type: number
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Product added to the day
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/private/day/{date}/consumed/{productId}:
    delete:
      summary: Delete a consumed product from a specific day
      tags:
        - Day
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer your_jwt_token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Product removed
        '404':
          description: Day or product not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        kcal:
          type: number
        weight:
          type: number
        category:
          type: string

    ConsumedProduct:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/Product'
        weight:
          type: number
